version: '3'

volumes:
  static:
  code:

services:
  db:
    image: postgres
    ports:
      - '5432'
  redis:
    image: redis
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - code:/code
      - static:/static
    depends_on:
      - web
    entrypoint: "/code/scripts/entrypoint.nginx.sh"
  web:
    build: .
    env_file:
      - ./config/env/local.env
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/bootstrap.sh"]
    volumes:
      - code:/code
      - static:/static
    expose:
      - "8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis